
server:
  port:
    8010
    
spring:
  datasource:
    url:
      jdbc:mysql://localhost:3306/music?useSSL=false
    username:
      root
    password:
      root
    driver-class-name:
      com.mysql.jdbc.Driver
